apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hackaton-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hackaton-api
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70